services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
        - .:/var/www/html
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: dockerFiles
      dockerfile: Dockerfile
    volumes: 
      - .:/var/www/html/
    depends_on:
      - postgres

  postgres:
    image: postgres:17.4 
    container_name: postgres 
    platform: linux/amd64
    restart: always
    ports: 
      - "5432:5432"
    env_file:
    - .env 
    volumes:
      - psql_data:/var/lib/postgresql/data

 

volumes:
  psql_data:

