services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8999:80"
    volumes:
        - .:/var/www/html
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: dockerFiles
      dockerfile: Dockerfile
    volumes: 
      - .:/var/www/html/
    ports:
      - "9004:9003"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres 
    platform: linux/amd64
    restart: always
    ports: 
      - "5434:5432"
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: users
    volumes:
      - psql_data:/var/lib/postgresql/data

 

volumes:
  psql_data:

